baseURL = "https://leeminhquang.github.io/blog-laptrinh/"
languageCode = "vi"
title = "Blog Lập Trình Mạng"
theme = "PaperMod"
pagination.pageSize = 10
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "profile"
    name = "Profile"
    url = "/about/"
    weight = 3

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  author = "Lê Minh Quang"
  description = "Sinh viên An ninh mạng | Lập trình mạng | AI ứng dụng"
  customCSS = [
    "css/extended/professional.css"
  ]

  [params.assets]
    favicon = "/images/avatar.jpg"
    disableHLJS = false

# Quan trọng: profileMode là BẢNG, không phải bool
[params.profileMode]
  enabled = true
  title = "Blog Lập Trình Mạng"
  subtitle = "Sinh viên An ninh mạng • Lập trình mạng • Java & JavaScript"
  imageUrl = "/images/avatar.jpg"
  imageTitle = "Ảnh đại diện"
  imageWidth = 160
  imageHeight = 160

  [[params.profileMode.buttons]]
    name = "Blog"
    url  = "/posts/"

  [[params.profileMode.buttons]]
    name = "Profile"
    url  = "/about/"
