baseURL = "https://leeminhquang.github.io/blog-laptrinh/"
languageCode = "vi"
title = "Blog Lập Trình Mạng"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "profile"
    name = "Profile"
    url = "/about/"
    weight = 3


[params]
  author = "Lê Minh Quang"
  description = "Sinh viên An ninh mạng | Lập trình mạng | AI ứng dụng"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true
  customCSS = ["css/extended/professional.css"]

  [params.assets]
    favicon = "/images/avatar.jpg"
    disableHLJS = false

  [params.profileMode]
    enabled = true
    title = "Lê Minh Quang"
    subtitle = "Sinh viên An ninh mạng • Lập trình mạng • AI ứng dụng"
    imageUrl = "/images/avatar.jpg"
    imageTitle = "Ảnh đại diện"
    imageWidth = 160
    imageHeight = 160

    [[params.profileMode.buttons]]
      name = "Bài viết"
      url  = "/posts/"

    [[params.profileMode.buttons]]
      name = "Hồ sơ"
      url  = "/about/"


[markup]
  [markup.goldmark.renderer]
    unsafe = true
